services:
  portfolio-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: weversonlemos/portfolio:latest
    container_name: portfolio-prod
    restart: always
    ports:
      - "80:80"
